# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c9a8219354c23ab77eee3bde5f131a31f46335a340ddaa37e37e52d1ddba39fc0b71742a69f680025a7247be4b452b409093ed10ad4a9ad8a15aeb6928f4a05

test:
  secret_key_base: 69b517777f9e4c881ce4e4f4289e653355d63c1a88064de24729e3d9c3d7e89497b95d09f83c3e9fedb1c1ece96e4cb87168d3754b08f54ae9e7a9c209a12b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
